services:
  redis:
    image: redis:4-alpine
    volumes:
      - ./data:/data

  github-trending:
    image: k8scat/github-trending:latest
    depends_on:
      - redis
    environment:
      - TRENDING_LANGUAGE=go
      - OPENAI_API_BASE=https://api.openai-all.com
      - OPENAI_API_KEY=sk-xxx
      - OPENAI_MODEL=gpt-4o
    volumes:
      - ./config.toml:/config.toml
