version: "3"

services:
  redis:
    image: redis:4-alpine
    networks:
      - rust_trending_net
    volumes:
      - /srv/rust-trending/data:/data

  bot:
    image: ghcr.io/k8scat/rust-trending:latest
    depends_on:
      - redis
    environment:
      - RUST_LOG=info
    volumes:
      - /srv/rust-trending/config.toml:/config.toml
    networks:
      - rust_trending_net

networks:
  rust_trending_net:
