name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'k8scat/go-trending'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --platform linux/amd64 . -t ghcr.io/k8scat/go-trending:latest --push
